name: flutter_login_screen
description: Functional Flutter Starter Kit
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  permission_handler: ^5.0.1+1
  page_view_indicators: 1.3.1
  shared_preferences: 0.5.6
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.0+1
  cloud_firestore: ^0.16.0
  progress_dialog: ^1.2.4
  favorite_button: ^0.0.3
  flutter_facebook_login: 3.0.0
  http: 0.12.2
  image_picker: ^0.6.7+21
  carousel_slider: ^2.3.1
  firebase_storage: ^7.0.0
  cached_network_image: ^2.5.0
  flutter_slidable: ^0.5.7

  lottie: ^0.7.0+1
  flutter_swiper: ^1.1.6
  simple_animations: ^1.3.3
  rounded_loading_button: ^1.0.18
  url_launcher: ^5.7.10
  build_web_compilers: ^2.12.2
  firebase_database: ^6.0.0
  flutter:
    sdk: flutter
  share: any
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
  - assets/images/
