name: flutter_login_screen
description: Functional Flutter Starter Kit
version: 4.1.0+12

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:

  flutter_social_content_share: ^0.0.4
  permission_handler: ^5.0.1+1
  flutter_facebook_login: ^2.0.1
  page_view_indicators: 1.3.1
  shared_preferences: 0.5.6
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.0+1
  cloud_firestore: ^0.16.0
  progress_dialog: ^1.2.4
  favorite_button: ^0.0.3
  http: 0.12.2
  image_picker: ^0.6.7+21
  carousel_slider: ^2.3.1
  firebase_storage: ^7.0.0
  cached_network_image: ^2.5.0
  flutter_slidable: ^0.5.7
  lottie: ^0.7.0+1
  flutter_swiper: ^1.1.6
  simple_animations: ^1.3.3
  rounded_loading_button: ^1.0.18
  url_launcher: ^5.7.10
  build_web_compilers: ^2.12.2
  firebase_database: ^6.0.0
  package_info: ^2.0.0
  share: ^2.0.1
  country_picker: ^1.0.4
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  home_widget: ^0.1.2+1
  styled_widget: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  http:

flutter:

  uses-material-design: true
  assets:
  - assets/images/

